apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edc-backend-service.fullname" . }}
  labels:
    {{- include "edc-backend-service.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "edc-backend-service.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edc-backend-service.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "edc-backend-service.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP
          env:          
          - name: DEFAULT_EDC_HOSTNAME
            valueFrom: 
              secretKeyRef:
                name: {{ include "edc-backend-service.applicationSecret.name" . }}
                key: edchostname
          - name: DEFAULT_EDC_APIKEYHEADER
            valueFrom: 
              secretKeyRef:
                name: {{ include "edc-backend-service.applicationSecret.name" . }}
                key: edcapikeyheader
          - name: DEFAULT_EDC_APIKEY
            valueFrom: 
              secretKeyRef:
                name: {{ include "edc-backend-service.applicationSecret.name" . }}
                key: edcapikey

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
