{{- if .Values.ingress.enabled -}}
{{- $fullName := include "edc-backend-service.fullname" . -}}
{{- $ingressExtraPaths := .Values.ingress.extraPaths -}}
{{- $svcName := include "edc-backend-service.fullname" . -}}
{{- $svcPort := .Values.service.port -}}
{{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1
{{- else if semverCompare ">=1.14-0" .Capabilities.KubeVersion.GitVersion -}}
apiVersion: networking.k8s.io/v1beta1
{{- else -}}
apiVersion: extensions/v1beta1
{{- end }}
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "edc-backend-service.labels" . | nindent 4 }}
  {{- with .Values.ingress.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- if .Values.ingress.tls.enabled }}
  tls:
    - hosts:
        - {{ .Values.ingress.tls.host }}
      #secretName: "{{ include "edc-backend-service.fullname" . }}-tls"
      secretName: "{{ .Values.ingress.tls.secretName }}"
  {{- end }}
  ingressClassName: {{ .Values.ingress.className }}
  rules:
  - host: {{ .Values.ingress.tls.host }}
    http:
      paths:
      - path: {{ default "/" .Values.ingress.pathPrefix | quote }}
        pathType: Prefix
        backend:
          {{- if semverCompare ">=1.20-0" .Capabilities.KubeVersion.GitVersion }}
          service:            
            name: {{ $svcName }}
            port:
              number: {{ $svcPort }}
          {{- else }}
          {{- if $.Values.service.servicename }}
            serviceName: {{ $.Values.service.servicename }}
          {{- else }}
            serviceName: {{ default $svcName .service }}
          {{- end }}
            servicePort: {{ default $svcPort .port }}
          {{- end }}
{{- end }}
